# Generated by Django 5.0.6 on 2026-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_category_user_expense_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
